### PR TITLE
Deploy to dokku

### PR DESCRIPTION
**Pull request by hexylena**
1. A github action has been added, @bebatut I will send you a secret key that must be added to the github actions.
2. I've ignored the `db_config.py` configuration option, as Dokku exposes a linked database's details as an environment variable to your application. Thus we can create the connection directly from that environment variable, without ever needing to put the connection parameters (host/password/etc) in any git repository, or even know about them.
3. Beware migrations. Because you're using 4 gunicorn workers, and don't have an explicit "Migrate table" command you can run (a la django's `manage.py migrate`), they all compete to create or migrate tables and will crash the initial deployment. This could be fixed by having a specific command to run the migration, and then including it as a pre-deploy step. e.g. https://github.com/hexylena/movie-club-bot/blob/main/app.json)
4. I have just moved `db_config.py.in` to `db_config.py`, it was an unnecessary step and this allows the deployment to succeed without doing a strange dance of creating that file mid-deploy which doesn't fit with the dokku/heroku model.
5. If there is energy in a future version I would encourage uniform use of sqlalchemy rather than raw psycopg2 in one part of the service and SA in other places.

### CODE REVIEW

**Comment by hexylena** [comment]
https://dnanalyzer.apps.galaxyproject.eu/ it's live here :)

**Comment by YedilSerzhan** [comment]
Thank you very much for the suggestions and improvements!  @hexylena 
It seems the backend-database connection is not up, since the questions and chapters are not loaded from the database, and the login/register functions don't seem to work either. Would you mind looking at why this is happening?

**Comment by hexylena** [comment]
>  It seems the backend-database connection is not up, since the questions and chapters are not loaded from the database, and the login/register functions don't seem to work either. Would you mind looking at why this is happening?

huh, that's quite odd. I see the following:

1. database is up
2. can be accessed from where dnanalyzer is running
3. user table is populated
    ```
    dnanalyzer=# select * from users limit 1;
     id | username |                                         password                                         
    ----+----------+------------------------------------------------------------------------------------------
      1 | test1    | sha256$qZxZpYd0RbMivRsb$1a76fcbade40ab9256750bceacae474434a7a3b9506e9f2ddfc6f8d02033433c
    (1 row)
    ```
4. The following traceback in the logs
    
    ```
    [2023-01-06 10:46:20,400] ERROR in app: Exception on /level/1/chapter/1 [GET]
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
        response = self.full_dispatch_request()
      File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
        rv = self.dispatch_request()
      File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
        return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
      File "/app/routes/main.py", line 103, in chapter
        chapter_dump, questions_dump = quiz_questions_helper(cur_chapter[0]['id'])
    IndexError: list index out of range
    ```

It seems that `init_yaml_to_db` was never run. I've run that by hand:

```
root@95ada12dfc63:/app# .heroku/python/bin/python3 init_yaml_to_db.py 
successfully emptied database tables
successfully loaded data for level table
successfully loaded data to tables
root@95ada12dfc63:/app# psql $DATABASE_URL 
psql (14.4 (Ubuntu 14.4-1.pgdg20.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

dnanalyzer=# select * from question limit 1;
 id |                    title                    | description |    type    |                                                                                                                 hint                                                                                                                  |                                              explanation                                               | image_name | point | chapter_id 
----+---------------------------------------------+-------------+------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+------------+-------+------------
  1 | What is the proper definition of evolution? |             | choose_one | Even though evolution is taking place all around us, for many species the process operates so slowly that it is not observable except over thousands or hundreds of thousands of years, much too long to witness in a human lifetime. | Evolution is a change in a population of organisms through time leading to the appearance of new forms |            |     4 |          1
(1 row)
```

This is clearly something missing in the deployment. @YedilSerzhan is that script safe to run every time at boot? (Will it create multiple entries or destroy user answers or so?)

**Comment by YedilSerzhan** [comment]
I think everything is working now! 

The reason for running this script on every boot is that it was requested in the user requirements to "store the questions in chapter YAML files so that non-technical people can contribute to them as well". And if some questions were added between chapters, it would be hard to distinguish them and add them to the database. So not it's working like dropping them all and re-entering them. the design of the database does not follow the third normal form (leaving out some foreign keys) so that the user's answers are not dropped along.

**Comment by hexylena** [comment]
> The reason for running this script on every boot

ok, so it *is* **safe** to run on every restart of the server. I'll add that into this PR then.

**Comment by bebatut** [comment]
Thanks @hexylena for the PR and deploying it

**Comment by teresa-m** [comment]
Thanks so much to all of you!! It looks really great!

**Pull request merged**
